using TianyiVision.Acis.Core.Contracts;
using TianyiVision.Acis.Core.Localization;

namespace TianyiVision.Acis.Infrastructure.Localization;

public sealed class TerminologyCatalogProvider : ITerminologyCatalogProvider
{
    public IReadOnlyList<TerminologyProfile> GetProfiles()
    {
        var baseTextEntries = CreateBaseTextEntries();

        return
        [
            new TerminologyProfile(
                "telecom",
                "标准电信版",
                baseTextEntries,
                new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    [TerminologyVariables.PointNameTerm] = "点位",
                    [TerminologyVariables.InspectionTerm] = "巡检",
                    [TerminologyVariables.FaultTerm] = "故障",
                    [TerminologyVariables.HandlerTerm] = "排障维护人",
                    [TerminologyVariables.ReviewTerm] = "复核",
                    [TerminologyVariables.DispatchPoolTerm] = "派单池"
                }),
            new TerminologyProfile(
                "security",
                "通用安防版",
                baseTextEntries,
                new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    [TerminologyVariables.PointNameTerm] = "监控点",
                    [TerminologyVariables.InspectionTerm] = "巡查",
                    [TerminologyVariables.FaultTerm] = "告警",
                    [TerminologyVariables.HandlerTerm] = "处置人员",
                    [TerminologyVariables.ReviewTerm] = "复核",
                    [TerminologyVariables.DispatchPoolTerm] = "派单池"
                }),
            new TerminologyProfile(
                "tourism",
                "文旅景区版",
                baseTextEntries,
                new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    [TerminologyVariables.PointNameTerm] = "景观点",
                    [TerminologyVariables.InspectionTerm] = "巡看",
                    [TerminologyVariables.FaultTerm] = "异常",
                    [TerminologyVariables.HandlerTerm] = "保障人员",
                    [TerminologyVariables.ReviewTerm] = "复核",
                    [TerminologyVariables.DispatchPoolTerm] = "派单池"
                })
        ];
    }

    private static IReadOnlyDictionary<string, string> CreateBaseTextEntries()
    {
        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [TextTokens.ApplicationName] = "天翼视联 AI 智能巡检系统",
            [TextTokens.ShellCurrentUserLabel] = "当前用户",
            [TextTokens.ShellCurrentUserValue] = "本地管理员",
            [TextTokens.ShellCurrentTimeLabel] = "当前时间",
            [TextTokens.ShellSearchPlaceholder] = "全局搜索入口预留",
            [TextTokens.ShellThemeEntry] = "主题入口",
            [TextTokens.ShellSettingsEntry] = "设置入口",
            [TextTokens.ShellHeaderInspectionTasks] = "今日{inspection_term}任务",
            [TextTokens.ShellHeaderFaults] = "今日{fault_term}数",
            [TextTokens.ShellHeaderOutstanding] = "未恢复{fault_term}",
            [TextTokens.ShellHeaderRecovered] = "今日恢复数",
            [TextTokens.ShellHeaderPendingReview] = "待{review_term}任务",
            [TextTokens.ShellHeaderPendingDispatch] = "待派单数",
            [TextTokens.ShellHeaderFeedbackIdle] = "状态条支持轻量点击反馈，本轮不做复杂跳转。",
            [TextTokens.ShellHeaderFeedbackPattern] = "已选中“{0}”，后续可衔接模块跳转与筛选。",
            [TextTokens.NavigationHome] = "首页",
            [TextTokens.NavigationInspection] = "AI{inspection_term}",
            [TextTokens.NavigationDispatch] = "{fault_term}派单处理",
            [TextTokens.NavigationReports] = "报表中心",
            [TextTokens.NavigationSettings] = "系统设置",
            [TextTokens.HomeTitle] = "首页总览",
            [TextTokens.HomeDescription] = "围绕首版三大业务模块提供总览入口，本轮仅交付稳定可启动的总览壳层。",
            [TextTokens.HomeMetricTasks] = "今日{inspection_term}任务数",
            [TextTokens.HomeMetricPoints] = "今日{point_name_term}数",
            [TextTokens.HomeMetricFaults] = "今日{fault_term}数",
            [TextTokens.HomeMetricRecovered] = "今日恢复数",
            [TextTokens.HomeMetricOutstanding] = "当前未恢复{fault_term}数",
            [TextTokens.HomeMetricPendingReview] = "待{review_term}任务数",
            [TextTokens.HomeMetricPendingDispatch] = "待派单数",
            [TextTokens.HomeMapStageBadge] = "MAP STAGE",
            [TextTokens.HomeMapStageTitle] = "首页地图主舞台",
            [TextTokens.HomeMapStageDescription] = "地图在首页承担主视觉与主态势展现，当前用假数据模拟重点点位、故障点位和巡检中点位联动。",
            [TextTokens.HomeMapStageHint] = "点击地图点位或左侧最近故障，可同步刷新左右摘要带；后续这里直接替换为真实地图中台。",
            [TextTokens.HomeMapLegendFault] = "{fault_term}点位",
            [TextTokens.HomeMapLegendNormal] = "正常点位",
            [TextTokens.HomeMapLegendKey] = "重点点位",
            [TextTokens.HomeMapLegendInspecting] = "{inspection_term}中点位",
            [TextTokens.HomeLeftSummaryTitle] = "左侧辅助摘要",
            [TextTokens.HomeLeftSummaryDescription] = "保留当前巡检组、执行进度、最近故障和待处理提醒，不堆叠图表与大卡片。",
            [TextTokens.HomeCurrentGroupLabel] = "当前{inspection_term}组",
            [TextTokens.HomeExecutionProgressLabel] = "今日{inspection_term}执行进度",
            [TextTokens.HomePendingReviewLabel] = "待{review_term}任务提醒",
            [TextTokens.HomePendingDispatchLabel] = "待派单摘要",
            [TextTokens.HomeRecentFaultsTitle] = "最近{fault_term}{point_name_term}",
            [TextTokens.HomeRecentFaultsDescription] = "点击左侧故障项后，与地图点位和右侧摘要同步联动。",
            [TextTokens.HomeRecentFaultTimeLabel] = "最近故障时间",
            [TextTokens.HomeRightSummaryTitle] = "当前选中{point_name_term}摘要",
            [TextTokens.HomeRightSummaryDescription] = "右侧只保留当前点位摘要和后续快捷入口占位，不替代独立业务页面。",
            [TextTokens.HomeSelectedPointStatusLabel] = "当前状态",
            [TextTokens.HomeSelectedPointFaultTypeLabel] = "{fault_term}类型",
            [TextTokens.HomeSelectedPointSummaryLabel] = "简版说明",
            [TextTokens.HomeSelectedPointActionLabel] = "快捷入口占位",
            [TextTokens.HomeSelectedPointActionHint] = "后续在此承接进入 AI 巡检页、复核墙或派单处理页的快捷入口。",
            [TextTokens.HomeTaskPanelTitle] = "任务摘要",
            [TextTokens.HomeTaskPanelDescription] = "保留当前巡检组、执行进度、待复核和待派单提醒。",
            [TextTokens.HomeFaultPanelTitle] = "最近故障",
            [TextTokens.HomeFaultPanelDescription] = "点击列表项后，与地图点位和右侧选中摘要同步联动。",
            [TextTokens.HomePointPanelTitle] = "选中点位摘要",
            [TextTokens.HomePointPanelDescription] = "仅做当前点位轻摘要，不替代完整业务面板。",
            [TextTokens.HomeLegendPanelTitle] = "图例",
            [TextTokens.HomePanelRestoreHint] = "已关闭面板可在地图右上角恢复。",
            [TextTokens.HomeMapSelectionHint] = "点击地图点位后，右侧摘要和左下故障项将同步刷新。",
            [TextTokens.InspectionTitle] = "AI{inspection_term}",
            [TextTokens.InspectionDescription] = "遵循基线的三栏式工作区，当前页仅用假数据模拟任务区、中台态势和右侧详情联动。",
            [TextTokens.InspectionTasksTitle] = "{inspection_term}任务区",
            [TextTokens.InspectionTasksDescription] = "保留巡检组切换、策略摘要、执行控制与最近故障点位列表。",
            [TextTokens.InspectionGroupTitle] = "{inspection_term}组选择区",
            [TextTokens.InspectionGroupDescription] = "后续承接接口设备组合、组级策略和组级派单配置。",
            [TextTokens.InspectionGroupCurrentLabel] = "当前{inspection_term}组",
            [TextTokens.InspectionGroupAvailableLabel] = "可切换{inspection_term}组",
            [TextTokens.InspectionStrategyTitle] = "{inspection_term}策略摘要",
            [TextTokens.InspectionStrategyDescription] = "展示当前巡检组的执行节奏、结果处理模式与派单模式。",
            [TextTokens.InspectionStrategyFirstRunLabel] = "首次执行时间",
            [TextTokens.InspectionStrategyDailyRunsLabel] = "每日执行次数",
            [TextTokens.InspectionStrategyIntervalLabel] = "任务时间间隔",
            [TextTokens.InspectionStrategyResultModeLabel] = "结果处理模式",
            [TextTokens.InspectionStrategyDispatchModeLabel] = "派单模式",
            [TextTokens.InspectionExecutionTitle] = "任务执行状态",
            [TextTokens.InspectionExecutionDescription] = "保留今日已执行次数、当前任务状态、下一次执行时间和当前进度。",
            [TextTokens.InspectionExecutionExecutedTodayLabel] = "今日已执行次数",
            [TextTokens.InspectionExecutionTaskStatusLabel] = "当前任务状态",
            [TextTokens.InspectionExecutionNextRunLabel] = "下一次执行时间",
            [TextTokens.InspectionExecutionProgressLabel] = "当前进度",
            [TextTokens.InspectionExecutionSimulationLabel] = "模拟说明",
            [TextTokens.InspectionActionExecute] = "立即执行本组{inspection_term}",
            [TextTokens.InspectionActionHistory] = "查看历史任务",
            [TextTokens.InspectionActionEnable] = "启用本组",
            [TextTokens.InspectionActionDisable] = "停用本组",
            [TextTokens.InspectionActionOpenReviewWall] = "进入{inspection_term}结果{review_term}页",
            [TextTokens.InspectionRecentFaultsTitle] = "最近{fault_term}{point_name_term}",
            [TextTokens.InspectionRecentFaultsDescription] = "点击列表项后，与中台点位和右侧详情双向联动。",
            [TextTokens.InspectionRecentFaultTimeLabel] = "最近故障时间",
            [TextTokens.InspectionWorkbenchTitle] = "地图中台态势区",
            [TextTokens.InspectionWorkbenchDescription] = "当前使用可扩展点位态势模拟层，后续可直接替换为真实地图控件。",
            [TextTokens.InspectionWorkbenchMapBadge] = "MAP WORKSPACE",
            [TextTokens.InspectionWorkbenchHint] = "当前为演示态势层，后续接入真实地图后保持相同的点位状态模型和联动方式。",
            [TextTokens.InspectionRunSummaryStartedAtLabel] = "本轮开始时间",
            [TextTokens.InspectionRunSummaryTotalPointsLabel] = "总点位数",
            [TextTokens.InspectionRunSummaryInspectedPointsLabel] = "已巡检数",
            [TextTokens.InspectionRunSummaryNormalLabel] = "正常数",
            [TextTokens.InspectionRunSummaryFaultLabel] = "故障数",
            [TextTokens.InspectionRunSummaryCurrentPointLabel] = "当前巡检点位",
            [TextTokens.InspectionLegendPending] = "待{inspection_term}",
            [TextTokens.InspectionLegendActive] = "{inspection_term}中高亮",
            [TextTokens.InspectionLegendNormal] = "{inspection_term}正常",
            [TextTokens.InspectionLegendFault] = "{fault_term}红灯闪烁",
            [TextTokens.InspectionLegendSilent] = "静默不{inspection_term}",
            [TextTokens.InspectionLegendPaused] = "恢复前暂停{inspection_term}",
            [TextTokens.InspectionDetailsTitle] = "点位详情联动区",
            [TextTokens.InspectionDetailsDescription] = "支持点位点击和故障列表点击后同步刷新基础信息、状态说明和历史摘要。",
            [TextTokens.InspectionDetailBasicTitle] = "当前{point_name_term}基础信息",
            [TextTokens.InspectionDetailPointNameLabel] = "{point_name_term}名称",
            [TextTokens.InspectionDetailUnitLabel] = "所属单位",
            [TextTokens.InspectionDetailCurrentHandlingUnitLabel] = "当前处理单位",
            [TextTokens.InspectionDetailCurrentStatusLabel] = "当前状态",
            [TextTokens.InspectionDetailStatusTitle] = "{inspection_term}状态区",
            [TextTokens.InspectionDetailOnlineLabel] = "在线状态",
            [TextTokens.InspectionDetailPlaybackLabel] = "播放状态",
            [TextTokens.InspectionDetailImageLabel] = "画面状态",
            [TextTokens.InspectionDetailFaultTypeLabel] = "{fault_term}类型",
            [TextTokens.InspectionDetailFaultNoteLabel] = "简要{fault_term}说明",
            [TextTokens.InspectionPreviewTitle] = "视频预览占位区",
            [TextTokens.InspectionPreviewDescription] = "可播放点位显示预览占位样式，不可播放点位显示状态说明，后续直接替换为真实视频流容器。",
            [TextTokens.InspectionPreviewPlayableBadge] = "可播放预览",
            [TextTokens.InspectionPreviewUnavailableBadge] = "状态说明",
            [TextTokens.InspectionPreviewPlayableHint] = "当前点位可播放，后续在此接入实时视频流与截图能力。",
            [TextTokens.InspectionPreviewUnavailableHint] = "当前点位不可播放，后续在此展示播放失败原因和协议切换说明。",
            [TextTokens.InspectionPreviewPlayableCanvas] = "视频预览占位",
            [TextTokens.InspectionPreviewUnavailableCanvas] = "不可播放状态占位",
            [TextTokens.InspectionRecordTitle] = "{inspection_term}历史摘要",
            [TextTokens.InspectionRecordDescription] = "汇总最近一次故障时间、是否进入派单池与最近一次巡检结论。",
            [TextTokens.InspectionDetailHistoryTitle] = "历史摘要区",
            [TextTokens.InspectionDetailLastFaultLabel] = "最近一次故障时间",
            [TextTokens.InspectionDetailDispatchEntryLabel] = "是否进入派单池",
            [TextTokens.InspectionDetailLastConclusionLabel] = "最近一次巡检结论",
            [TextTokens.InspectionResultModeReview] = "上墙复核",
            [TextTokens.InspectionResultModeDirectDispatch] = "直接进入派单流程",
            [TextTokens.InspectionDispatchModeAuto] = "自动派单",
            [TextTokens.InspectionDispatchModeManual] = "人工派单",
            [TextTokens.InspectionTaskStatusIdle] = "待命中",
            [TextTokens.InspectionTaskStatusRunning] = "模拟执行中",
            [TextTokens.InspectionTaskStatusPaused] = "已停用",
            [TextTokens.InspectionTaskStatusCompleted] = "本轮模拟完成",
            [TextTokens.InspectionStatusPending] = "待巡检",
            [TextTokens.InspectionStatusInspecting] = "巡检中",
            [TextTokens.InspectionStatusNormal] = "巡检正常",
            [TextTokens.InspectionStatusFault] = "巡检故障",
            [TextTokens.InspectionStatusSilent] = "静默不巡检",
            [TextTokens.InspectionStatusPausedUntilRecovery] = "故障恢复前暂停巡检",
            [TextTokens.InspectionOnlineOnline] = "设备在线",
            [TextTokens.InspectionOnlineOffline] = "设备离线",
            [TextTokens.InspectionPlaybackPlayable] = "播放正常",
            [TextTokens.InspectionPlaybackFailed] = "播放失败",
            [TextTokens.InspectionImageNormal] = "画面正常",
            [TextTokens.InspectionImageAbnormal] = "画面异常",
            [TextTokens.InspectionFaultTypeOffline] = "设备离线",
            [TextTokens.InspectionFaultTypePlaybackFailed] = "设备在线 + 视频播放失败",
            [TextTokens.InspectionFaultTypeImageAbnormal] = "设备在线 + 画面异常",
            [TextTokens.InspectionFaultTypeNone] = "无",
            [TextTokens.InspectionDispatchPoolYes] = "进入派单池",
            [TextTokens.InspectionDispatchPoolNo] = "不进入派单池",
            [TextTokens.InspectionConclusionNormal] = "正常",
            [TextTokens.InspectionConclusionFault] = "故障",
            [TextTokens.InspectionSimulationTriggered] = "已触发一次模拟执行，当前点位与进度已刷新。",
            [TextTokens.InspectionSimulationCompleted] = "当前组内可巡检点位已全部完成模拟。",
            [TextTokens.InspectionHistoryPlaceholder] = "历史任务页后续承接任务记录、复核墙入口和执行明细。",
            [TextTokens.InspectionReviewWallBadge] = "REVIEW WALL",
            [TextTokens.InspectionReviewWallTitle] = "{inspection_term}结果{review_term}页",
            [TextTokens.InspectionReviewWallDescription] = "按基线要求将本轮参与巡检的点位全部上墙，便于集中人工复核与后续流程衔接。",
            [TextTokens.InspectionReviewSummaryDescription] = "汇总当前巡检组本轮任务结果、复核状态与复核进度。",
            [TextTokens.InspectionReviewTaskFinishedAtLabel] = "本轮任务结束时间",
            [TextTokens.InspectionReviewTaskReviewStatusLabel] = "当前{review_term}状态",
            [TextTokens.InspectionReviewTaskReviewedCountLabel] = "已{review_term}点位数",
            [TextTokens.InspectionReviewTaskTransitionHint] = "流程衔接提示",
            [TextTokens.InspectionReviewStatusPending] = "待复核",
            [TextTokens.InspectionReviewStatusReviewed] = "已复核",
            [TextTokens.InspectionReviewActionConfirmTask] = "确认本轮{review_term}完成",
            [TextTokens.InspectionReviewActionBackToInspection] = "返回{inspection_term}页",
            [TextTokens.InspectionReviewActionMarkReviewed] = "标记已复核",
            [TextTokens.InspectionReviewActionReviewed] = "已完成复核",
            [TextTokens.InspectionReviewFilterTitle] = "{review_term}筛选区",
            [TextTokens.InspectionReviewFilterDescription] = "支持按结果、单位、故障类型和是否进入派单池筛选，默认故障卡片优先。",
            [TextTokens.InspectionReviewFilterAll] = "全部",
            [TextTokens.InspectionReviewFilterNormal] = "正常",
            [TextTokens.InspectionReviewFilterFault] = "故障",
            [TextTokens.InspectionReviewFilterPendingOnly] = "仅待复核",
            [TextTokens.InspectionReviewFilterDispatchPool] = "进入{dispatch_pool_term}",
            [TextTokens.InspectionReviewFilterUnitLabel] = "按单位筛选",
            [TextTokens.InspectionReviewFilterFaultTypeLabel] = "按{fault_term}类型筛选",
            [TextTokens.InspectionReviewFilterAllUnits] = "全部单位",
            [TextTokens.InspectionReviewFilterAllFaultTypes] = "全部故障类型",
            [TextTokens.InspectionReviewWallSectionDescription] = "卡片墙默认按故障优先排序，支持滚动浏览，适合本轮全部点位上墙展示。",
            [TextTokens.InspectionReviewCardPreviewNormal] = "正常截图占位",
            [TextTokens.InspectionReviewCardPreviewFault] = "故障截图占位",
            [TextTokens.InspectionReviewCardPreviewPaused] = "暂停巡检占位",
            [TextTokens.InspectionReviewDetailDescription] = "点击卡片后，在右侧查看当前点位的完整复核信息和截图放大占位区。",
            [TextTokens.InspectionReviewDetailResultLabel] = "{inspection_term}结果",
            [TextTokens.InspectionReviewDetailReviewStatusLabel] = "{review_term}状态",
            [TextTokens.InspectionReviewDetailScreenshotLabel] = "本轮截图放大区",
            [TextTokens.InspectionReviewDetailReviewNoteLabel] = "{review_term}备注",
            [TextTokens.InspectionReviewNotePlaceholder] = "本轮仅预留备注承载区，后续接入人工复核意见、派单确认依据和流转记录。",
            [TextTokens.InspectionReviewTaskCompletedFeedback] = "本轮复核已完成，后续可在此衔接“复核后再进入派单流程”的确认动作。",
            [TextTokens.InspectionReviewTaskPendingFeedback] = "当前仍有待复核点位，本轮先保留状态壳层和流程提示。",
            [TextTokens.InspectionReviewItemReviewedFeedback] = "当前点位已标记为已复核，卡片墙和详情区状态已同步刷新。",
            [TextTokens.InspectionReviewDispatchTransitionPlaceholder] = "后续在此衔接“上墙复核完成后进入派单池”的流程说明与触发入口。",
            [TextTokens.DispatchTitle] = "{fault_term}派单处理",
            [TextTokens.DispatchDescription] = "遵循左筛选区、中工单列表、右详情区结构，不引入复杂状态机。",
            [TextTokens.DispatchFilterTitle] = "{fault_term}池筛选区",
            [TextTokens.DispatchFilterDescription] = "预留按巡检组、单位、责任人、故障类型和快捷状态筛选。",
            [TextTokens.DispatchStatusTitle] = "状态快捷筛选",
            [TextTokens.DispatchStatusDescription] = "保留待派单、已派单、未恢复、已恢复、自动派单、人工派单等入口。",
            [TextTokens.DispatchListTitle] = "工单列表区",
            [TextTokens.DispatchListDescription] = "后续展示极简工单主状态与恢复状态，并承接同点位同故障合并策略。",
            [TextTokens.DispatchMergeTitle] = "重复{fault_term}合并规则",
            [TextTokens.DispatchMergeDescription] = "预留首次时间、最近时间、重复次数与最新截图字段。",
            [TextTokens.DispatchDetailTitle] = "工单详情区",
            [TextTokens.DispatchDetailDescription] = "后续承接基础信息、责任归属、通知记录与恢复确认。",
            [TextTokens.DispatchEvidenceTitle] = "{fault_term}证据区",
            [TextTokens.DispatchEvidenceDescription] = "预留截图、说明和恢复前后证据对比能力。",
            [TextTokens.ReportsTitle] = "报表中心",
            [TextTokens.ReportsDescription] = "首版只围绕巡检执行、故障统计、派单处置、责任归属和重点未恢复清单。",
            [TextTokens.ReportsFilterTitle] = "筛选区",
            [TextTokens.ReportsFilterDescription] = "预留时间范围、巡检组、当前处理单位、故障类型筛选。",
            [TextTokens.ReportsMetricInspection] = "{inspection_term}执行报表",
            [TextTokens.ReportsMetricFault] = "{fault_term}统计报表",
            [TextTokens.ReportsMetricDispatch] = "派单处置报表",
            [TextTokens.ReportsMetricOutstanding] = "重点未恢复{fault_term}清单",
            [TextTokens.ReportsChartTrendTitle] = "{fault_term}趋势图",
            [TextTokens.ReportsChartTrendDescription] = "预留趋势数据展示和图表联动过滤逻辑。",
            [TextTokens.ReportsChartTypeTitle] = "{fault_term}类型占比图",
            [TextTokens.ReportsChartTypeDescription] = "后续接入离线、播放失败、画面异常等首版故障类型。",
            [TextTokens.ReportsChartRecoveryTitle] = "派单与恢复趋势图",
            [TextTokens.ReportsChartRecoveryDescription] = "预留派单量、恢复量与闭环结果联动展示。",
            [TextTokens.ReportsTableTitle] = "明细表区",
            [TextTokens.ReportsTableDescription] = "预留五类报表切换、查看与导出入口。",
            [TextTokens.SettingsTitle] = "系统设置",
            [TextTokens.SettingsDescription] = "本轮不展示底层接入参数，仅保留主题、术语和本地配置说明入口。",
            [TextTokens.SettingsThemeCenterTitle] = "主题中心预留",
            [TextTokens.SettingsThemeCenterDescription] = "基于统一主题令牌预置三套主题方案，后续支持复制、预览和另存为自定义主题。",
            [TextTokens.SettingsTerminologyCenterTitle] = "术语中心预留",
            [TextTokens.SettingsTerminologyCenterDescription] = "基于术语变量和方案级覆盖，后续支持行业术语切换与单项微调。",
            [TextTokens.SettingsConfigTitle] = "本地配置说明",
            [TextTokens.SettingsConfigDescription] = "API 地址、Token、Key、webhook 等底层参数统一走本地配置文件读取，不在界面展示。",
            [TextTokens.SettingsStructureTitle] = "骨架扩展说明",
            [TextTokens.SettingsStructureDescription] = "当前解决方案已为 AI 巡检、派单处理、报表、主题中心和术语中心预留稳定分层与页面入口。",
            [TextTokens.SettingsActiveTheme] = "当前主题",
            [TextTokens.SettingsActiveTerminology] = "当前术语方案",
            [TextTokens.SettingsAvailableThemes] = "预设主题",
            [TextTokens.SettingsAvailableTerminologies] = "预设术语方案"
        };
    }
}
